{"name": "test_login_01_error[test_info0]", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'afters'", "trace": "self = <allure_commons._allure.fixture object at 0x0394CC70>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n>       with self:\n\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\_allure.py:184: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\_allure.py:188: in __enter__\n    plugin_manager.hook.start_fixture(parent_uuid=self._parent_uuid,\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_pytest\\listener.py:52: in start_fixture\n    self.allure_logger.start_after_fixture(parent_uuid, uuid, after_fixture)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.reporter.AllureReporter object at 0x0374BFA0>\nparent_uuid = 'a7432fb7-9a5a-4c49-be22-d51462683f37'\nuuid = '195971a0-b6a3-4d4a-8a56-68519730dfca'\nfixture = TestAfterResult(name='manage_browser::0', status=None, statusDetails=None, stage=None, description=None, descriptionHtml=None, steps=[], attachments=[], parameters=[], start=1581909398861, stop=None)\n\n    def start_after_fixture(self, parent_uuid, uuid, fixture):\n>       self._items.get(parent_uuid).afters.append(fixture)\nE       AttributeError: 'NoneType' object has no attribute 'afters'\n\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\reporter.py:60: AttributeError"}, "description": "手机号码为空", "parameters": [{"name": "test_info", "value": "{'mobile': '', 'pwd': '', 'expected': '请输入手机号'}"}], "start": 1581909396880, "stop": 1581909398860, "uuid": "418eeb1f-1bd7-4688-ac90-2560c2ae6079", "historyId": "c084e4389fca48677ce152c15f80ff49", "testCaseId": "257d7845b1b08b3f4759795efe78c533", "fullName": "test_case.test_login_pytest.TestLogin#test_login_01_error", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "WIN10-20180902D"}, {"name": "thread", "value": "20044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login_pytest"}]}