{"name": "test_login_01_error[test_info1]", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'afters'", "trace": "self = <allure_commons._allure.fixture object at 0x04BCBDF0>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n>       with self:\n\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\_allure.py:184: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\_allure.py:188: in __enter__\n    plugin_manager.hook.start_fixture(parent_uuid=self._parent_uuid,\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_pytest\\listener.py:52: in start_fixture\n    self.allure_logger.start_after_fixture(parent_uuid, uuid, after_fixture)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.reporter.AllureReporter object at 0x045D12C8>\nparent_uuid = '6b80e7eb-e42b-4828-bdd7-a1ebfe592b63'\nuuid = '7162c2ad-df93-4d05-ba1e-ceebd819fa88'\nfixture = TestAfterResult(name='manage_browser::0', status=None, statusDetails=None, stage=None, description=None, descriptionHtml=None, steps=[], attachments=[], parameters=[], start=1581845179731, stop=None)\n\n    def start_after_fixture(self, parent_uuid, uuid, fixture):\n>       self._items.get(parent_uuid).afters.append(fixture)\nE       AttributeError: 'NoneType' object has no attribute 'afters'\n\nC:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\allure_commons\\reporter.py:60: AttributeError"}, "description": "手机号码为空", "parameters": [{"name": "test_info", "value": "{'mobile': '123', 'pwd': '', 'expected': '请输入正确的手机号'}"}], "start": 1581845168873, "stop": 1581845179731, "uuid": "5b2127a4-b557-41af-a93f-d1790650d7d1", "historyId": "0012ce64218dd5599c4c9db563a66243", "testCaseId": "257d7845b1b08b3f4759795efe78c533", "fullName": "test_case.test_login_pytest.TestLogin#test_login_01_error", "labels": [{"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "WIN10-20180902D"}, {"name": "thread", "value": "31848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login_pytest"}]}